/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.control.gui;

import br.control.Beans.Mensali_bean;
import br.control.Controller.MatrAlu_controller;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joãomarcos
 */
public class MensalidadesAbertas extends javax.swing.JInternalFrame {

   DefaultTableModel tmMens = new DefaultTableModel (null, new String [] {"Código aluno","Nome" ,"Atividade","Valor mensalidade","Data de vencimento","Status"});
   List<Mensali_bean> mens = new ArrayList<>();
   ListSelectionModel lsmMens;
   int codAlu = 0;
   String nomeAlu = "";
   
    public MensalidadesAbertas() {
        initComponents();
        MatrAlu_controller controller = new MatrAlu_controller();
        
        try{
            controller.AdicionaNovaMensAosVenc();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
       try {
           mens = controller.ConsultaMensalisDeTodos();
           MostraPesquisaMens();
       } catch (SQLException ex) {
           Logger.getLogger(MensalidadesAbertas.class.getName()).log(Level.SEVERE, null, ex);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensa = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMens = new javax.swing.JTable();
        btnInfMen = new javax.swing.JButton();
        btnAtuTb = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mensalidades vencidas");

        panelMensa.setBackground(new java.awt.Color(255, 255, 255));

        tbMens.setModel(tmMens);
        tbMens.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmMens= tbMens.getSelectionModel();
        lsmMens.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent e){
                if (! e.getValueIsAdjusting()){
                    LinhaSelecionada(tbMens);
                }
            }
        });
        jScrollPane1.setViewportView(tbMens);

        btnInfMen.setText("Informações de mensalidade do aluno");
        btnInfMen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfMenActionPerformed(evt);
            }
        });

        btnAtuTb.setText("Atualizar informações");
        btnAtuTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtuTbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(272, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInfMen)
                    .addComponent(btnAtuTb))
                .addGap(58, 58, 58))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnInfMen)
                .addGap(18, 18, 18)
                .addComponent(btnAtuTb)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMensaLayout = new javax.swing.GroupLayout(panelMensa);
        panelMensa.setLayout(panelMensaLayout);
        panelMensaLayout.setHorizontalGroup(
            panelMensaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMensaLayout.setVerticalGroup(
            panelMensaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMensaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMensa.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMensa)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMensa)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInfMenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfMenActionPerformed
        ConsultaMatriculas m = new ConsultaMatriculas();
        centralizaForm(m);
        panelMensa.add(m);
        m.RecebeInf(codAlu, nomeAlu);
        m.setVisible(true);
    }//GEN-LAST:event_btnInfMenActionPerformed

    private void btnAtuTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtuTbActionPerformed
        MatrAlu_controller controller = new MatrAlu_controller();
       try {
           mens = controller.ConsultaMensalisDeTodos();
           MostraPesquisaMens();
       } catch (SQLException ex) {
           Logger.getLogger(MensalidadesAbertas.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_btnAtuTbActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtuTb;
    private javax.swing.JButton btnInfMen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDesktopPane panelMensa;
    private javax.swing.JTable tbMens;
    // End of variables declaration//GEN-END:variables

private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = panelMensa.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

public void MostraPesquisaMens(){
    while(tmMens.getRowCount()>0){ // enquanto as linhas forem zeradas, pega as linhas zeradas 
            tmMens.removeRow(0); // e as remove
            }
            if(mens.size() == 0){
        
            JOptionPane.showMessageDialog(this,"Nenhuma mensalidade pendente");
               }else{
                String[] linha = new String[] {null, null, null, null};
        for( int i=0; i <mens.size(); i++){
           //{"Código da mensalidade" ,"Data de vencimento","Atividade","Status"});
            tmMens.addRow(linha);
            tmMens.setValueAt(mens.get(i).getAluCod(), i, 0);
            tmMens.setValueAt(mens.get(i).getAluNome(), i, 1);
            tmMens.setValueAt(mens.get(i).getAtivNome(), i, 2);
            tmMens.setValueAt(String.valueOf("R$ "+mens.get(i).getMatrValMens()).replace(".", ","), i, 3);
            tmMens.setValueAt(String.valueOf(mens.get(i).getMensaliDtVenc()).replace("-", "/"), i, 4);
            tmMens.setValueAt(mens.get(i).getMensaliStatusPag(), i, 5);
            
               }
                }
}

private void LinhaSelecionada(JTable tabela){

        if (tbMens.getSelectedRow() != -1) {
            
            
            codAlu = Integer.valueOf(mens.get(tabela.getSelectedRow()).getAluCod());        
            nomeAlu = String.valueOf(mens.get(tabela.getSelectedRow()).getAluNome());
            
        }
    }
}
